### ISSUE TITLE
Web explorer shows every station offline for roughly 2 to 5 minutes out of every 10 minutes (but not all at same time)

### ISSUE THREAD

**Issue by Greg15** [WeatherXM/issue-tracker#130]
## WeatherXM Related Element
- Website (web explorer)
EDIT: also a variation in the in-app android explorer, added to "Describe the bug" section

## **Describe the bug**

VARIATION 1: WEB EXPLORER
The web explorer inaccurately shows online stations as offline roughly 2 to 5 minutes out of roughly every 10 minutes.

If you keep refreshing the web explorer when either displaying a hex tile (which displays the list of stations in the hex) or displaying a station tile, about 20 to 30 seconds after the page displays "10 minutes ago", the device status changes to offline. The issue is, the station is still online, but the web explorer just has outdated data for the next roughly 2 to 5 minutes. Monitoring the android app at the same time reveals that the device has actually sent data more frequently, but roughly only every other data transmission from the device is reflected in the web explorer. So it appears that the web explorer only *thinks* the device hasn't been seen in the last 10 minutes, even though the android app knows that the device has been seen more recently.

Depending on how the "10 minutes ago" is derived from possibly rounding or truncating the actual duration since the device was last seen, the display might change to "10 minutes ago" at 9.5 elapsed minutes or at 10 elapsed minutes since the explorer thinks data was last received from the device.
So the web explorer displaying offline might display around 10 elapsed minutes or 10.5 elapsed minutes since the web explorer thinks data was last received from the device.

If you continue refreshing the web explorer after the device shows offline, it will continue showing offline up to anywhere in the approximate range of "12 minutes ago" to "16 minutes ago". After that, additional refreshing of the web explorer will show data again in the rough range of "1 minute ago" to "5  minutes ago", and with that, the status reverts to online. 

To reiterate, concurrent monitoring of the android app during that period shows that data was actually transmitted and received during the time when the web explorer was counting up to the 12 to 16 minute range.

I have repeated the observation with more than 1 station.

VARIATION 2: IN-APP ANDROID EXPLORER
Similar scenario, except the switch to offline status happens either briefly before the displays changes to "10 minutes ago", or immediately upon changing to "10 minutes ago". To get the displayed station status to refresh, either swipe down on the station details or station list, or click anywhere on the map to have the station list disappear, then click back in the hex to get the station list again with refreshed data. 

POSSIBLE EXPLANATION:

In case it helps, this could be a possible explanation and solution...

I assume the web explorer is using data from an ETL process, and that the app is directly pulling from operational data rather than from an ETL database. I suspect the ETL process for the explorer runs somewhere in the range of every 10 to 15 minutes, and it currently runs very quickly (no more than a minute or 2). I also suspect that the online/offline logic is not part of the ETL, but instead is part of the explorer rendering logic, based on comparing the last seen timestamp to the current time. The logic to calculate online/offline status seems to be checking if the last seen timestamp is less than or greater than approximately 10 minutes.

If the ETL logic only runs about every 10 to 15 minutes, and because the transmission of data from devices will not be perfectly synchronized to finish transmitting 1 second before the ETL starts, then the last seen timestamp provided by the ETL output for a specific device will frequently be longer ago than 10 minutes.

It appears that the ETL is updated less frequently than the current online/offline status logic requires. The logic needs data updates more frequently than the ETL  is continuously providing under its current schedule.

POSSIBLE SOLUTION:

If the above guess is accurate, then I assume it is NOT scalable to run the ETL logic at least once every 5 minutes. If the above guess is accurate, then instead, one solution might be...

Keep the same ETL schedule (or even a longer ETL schedule), but change the logic for offline/online status, BUT ONLY CHANGE THAT LOGIC IN THE WEB EXPLORER AND IN-APP EXPLORER OR ANY PLACE THAT USES THE ETL OUTPUT. Do not change the online/offline logic in the part of the app where the home page data or station details page data seems to be pulled directly from operational data rather than from an ETL database.

So, the explorer possibly needs this altered logic for status...
Instead of offline meaning that it hasn't been seen in the last 10 minutes, it's offline for the purposes of the explorer if it hasn't been seen in 10 minutes since the ETL last started, which is the last time the ETL actually sampled the operational data. So, perhaps the explorer should say "Online as of {timestamp the ETL last started}", and "Offline as of {timestamp the ETL last started}".
That approach would even allow the ETL to run even less frequently if ever needed, without messing up the display of device statuses.

If using this approach, maybe add a note to the web explorer and in-app explorer similar to: "For performance reasons, the explorer uses data that is bulk processed periodically, and can be delayed compared to real-time data".
Or
"The explorer uses periodically processed data, and can be delayed compared to real-time data."

### **How To Reproduce**
Steps to reproduce the behavior for variation 1:
1. Identify a device that the android app says is online.
2. Go to the web explorer, and go either to the hex's station list that contains the device from step 1, or select in the web explorer the specific station identified in step 1 from the hex's station list.
3. If the station in the web explorer shows online, skip to step 4. If the station in the web explorer shows offline, then the "X minutes ago" shows 10 minutes or higher. Keep refreshing for up to 5 or 6 minutes until the "X minutes ago" reverts back to 1 to 6 minutes ago or so, and the device status reverts to online in the web explorer.
4. Constantly refresh the web page until the device reaches "10 minutes ago". The status will still display as online.
5. Start counting seconds, and continue to constantly refresh the web page. Somewhere around 20 to 30 seconds later, the device status in the web explorer will change to offline.
6. Quickly check the android app (refreshing the android app page if needed), and confirm that the device status is actually still online in the android app. Also notice that the android app shows "X minutes ago" somewhere in the range of 0 to 5 or 6 minutes ago. This confirms that the device has sent data recently and should be considered online.
7. Quickly go back to the web explorer, and refresh the page. Notice that it still shows offline in the web explorer.
8. Constantly refresh the web explorer, watching the "X minutes ago" count up. Continue this until the "X minutes ago" reverts to a small number again (0 to 6 minutes ago). The displayed status in the web explorer will then update to online.

Steps to reproduce the behavior for variation 2:
1. Use the in-app explorer instead of the web explorer.
2. To "refresh" the page, either swipe down from the station details or stations list, or, click off the tile in the in-app explorer to make the tile disappear. Then click on the hex again.
3. The status will switch to offline promptly as the time switches to "10 minutes ago" (or even in the last second or two of "9 minutes ago"), instead of taking 20 to 30 seconds into "10 minutes ago".

### **Expected behavior**
The device status in the web explorer should not say offline several minutes out of every 10 minutes, when it is actually online.
A difference should be identified between 1) the actual last seen timestamp being older than the threshold for "online", and 2) an outdated "last seen timestamp" due to a system implementation that delays access to the actual most recent "last seen timestamp".

See the 2nd half of the "Describe the bug" section for a proposed solution.

### **Screenshots**

VARIATION 1: WEB EXPLORER
![Screenshot_20220908-195807.png](https://user-images.githubusercontent.com/70354350/189262658-d1af9752-d888-40f8-bfeb-6396fc71ff47.png)
![Screenshot_20220908-195844.png](https://user-images.githubusercontent.com/70354350/189262680-892ca1d6-9fb9-49b8-aff8-34c3164d9357.png)

VARIATION 2: ANDROID IN-APP EXPLORER
![Screenshot_20220909-113522.png](https://user-images.githubusercontent.com/70354350/189408647-5210bc26-fdd1-4a20-b2ae-c9b4ee5200b4.png)
![Screenshot_20220909-113539.png](https://user-images.githubusercontent.com/70354350/189408671-e7677fb2-d43e-4b20-9db5-a47b6382a116.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: Moto g7 power 
 - OS: android version 10
 - Browser: Chrome 105.0.5195.77
 - Android App Version: 3.1.6-8f2bb6f

### **Additional context**
I accessed the web explorer using a browser on my phone rather than a desktop, so I listed device details for "Smartphone", even though the issue is with the web explorer rather than the android app. The android app was only used to confirm that the explorer data was incorrect.

Edit: similar issue added for in-app explorer.

NOTE: this bug also reveals that different logic seems to be used in the web explorer vs the in-app explorer, because it takes 20 seconds or so for the web explorer to change to offline after "10 minutes ago" is reached, but a station changes to offline in the android in-app explorer immediately as (or right before) "10 minutes ago" is reached.
So either the logic for offline is different, or the logic to round/truncate to display "10 minutes ago" is different.
I will submit this difference of logic as a separate issue, to make sure it doesn't get lost amongst the lengthy details of this submission.

**Comment by PavlosTze** [comment]
We have identified the issue and we have implemented a fix which will be included in the next API release. It's caching that caused this issue. Thank you for reporting that Greg! :)

**Comment by PavlosTze** [comment]
We just released a new API version which fixes this issue. Thank you :)

**Comment by Greg15** [comment]
I think there is still an opportunity for the issue to occur, just way less frequently.

I believe the M5 sends data about every 4.5 minutes. I can see that the data in the explorer is still one data broadcast behind the app, but only half of the time. This results in the situation I see where the "X minutes ago" can still get up to "9 minutes ago", before getting an up to date data broadcast of perhaps just 1 minute ago.

Normally, this seems like it will stay below the 10 minute threshold which would cause the status to be reported as offline.

But...

The "offline" status seems to kick in conceptually when the network can tell that 2 consecutive data broadcasts are missing rather than just 1 data broadcast being missed (at 10 minutes, 2 consecutive data broadcasts have been missed if transmissions start every 4.5 minutes and complete in less than 1 minute). If in reality only one data broadcast is actually not sent by the M5 before the M5 properly resumes sending data at the next attempt, then the station details in the app will immediately reflect the resumed data transmission and show as online. But, since the explorer appears to be delayed in getting every other data transmission, it's possible that the explorer promptly notices the missing data transmission, but the resumed data transmission is the transmission that is received on a delayed basis.

If this can happen, this would result in the explorer thinking it's been more than 10 minutes since the last received transmission, marking it as offline in the explorer, event though it would properly show as online in the app since the actual last data transmission would have been received within the last 5 minutes.
