### ISSUE TITLE
[Precipitation graph with zero/negative values]

### ISSUE THREAD

**Issue by kkatsoulak** [WeatherXM/issue-tracker#21]
## WeatherXM Related Element

- Android Application

## **Describe the bug**
When seeing historic data in precipitation graph the values are 0.00m but the is a bar graph showing that there is different values. There is even negative values to precipitation.

### **How To Reproduce**
1. Go to station in the app
2. Click on historical charts
3. Scroll down to precipitation and press different parts of the graph.
4. All values are displayed as 0.00mm and there is even a negative value -0.00mm

### **Expected behavior**
If all values are 0.00 then I would expect a zero value. I wouldn't expect a negative value at all.

### **Screenshots**
![Screenshot_2022-02-28-15-10-44-354_com.weatherxm.app.jpg](https://user-images.githubusercontent.com/100304233/155996443-50db7bba-651c-4806-a046-cc1885fc6d1c.jpg)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**

 - Android App Version 3.0.3-3f653e9

**Comment by PavlosTze** [comment]
@kkatsoulak Maybe this is related to the settings being reset as we discussed in another issue? Is the "mm" set in your settings?

**Comment by kkatsoulak** [comment]
I checked the historic values and up to the 24/02/2022 there is no problem with the display. It's set to mm. I see that the problem started yesterday 27/02/2022 after two days without rain.

![Screenshot_2022-02-28-18-10-41-809_com.weatherxm.app.jpg](https://user-images.githubusercontent.com/100304233/156017571-8d78b930-6ff5-4b55-a51a-b660027e52e7.jpg)

![Screenshot_2022-02-28-18-13-33-110_com.weatherxm.app.jpg](https://user-images.githubusercontent.com/100304233/156017826-63f97281-feb5-495d-983f-410686f33ca8.jpg)

**Comment by NikosTsiligaridis** [comment]
This issue is probably caused when the rain counter of the weather station overflows OR the weather station is reset via its reset button or battery replacement. In that case the M5 doesn't detect this rain counter reset and this might cause negative values. This is fixed in the latest version of M5 which will be rolled out soon.

**Comment by EmperorDRT1** [comment]
Has the M5 been updated to fix this bug? I'm still experiencing this behavior. 

![image](https://user-images.githubusercontent.com/44149620/159381327-08b38d7d-e78e-4e4e-b82d-02de0570333e.png)

**Comment by NikosTsiligaridis** [comment]
> This issue is probably caused when the rain counter of the weather station overflows OR the weather station is reset via its reset button or battery replacement. In that case the M5 doesn't detect this rain counter reset and this might cause negative values. This is fixed in the latest version of M5 which will be rolled out soon.

Yes :)
